sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tanviralamcse/cloud-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true tanviralamcse/cloud-docker npm run test