sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tanviralamcse/cloud-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true tanviralamcse/cloud-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  bucket_name: "tanvirdockerbucket"
  bucket_path: "docker"
  on:
    branch: master





  