sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tanviralamcse/cloud-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true tanviralamcse/cloud-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "cloud-docker"
  env: "Clouddocker-env"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  bucket_name: "elasticbeanstalk-ap-northeast-1-687141240283"
  bucket_path: "cloud-docker"
  on:
    branch: master





  